services:
  alimentos-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alimentos-web
    restart: unless-stopped
    ports:
      - "3300:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
