services:
  alimentos-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alimentos-web
    restart: unless-stopped
    ports:
      - "3300:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:/app/prisma/data/alimentos.db
    volumes:
      - ./data:/app/prisma/data
